from pydantic import Field, BaseModel
from data_science_agent.dtos.base.responses.visualization_base import VisualizationBase

class VisualizationContainerBase(BaseModel):
    """Contains all visualizations."""
    visualizations: list[VisualizationBase] = Field(..., description="The visualizations generated by the agent.")
