from pydantic import Field
from dtos.base.metadata_base import MetadataBase

class Code(MetadataBase):
    """Response format: code generated by the LLM followed by a short explanation of the code."""
    explanation: str = Field(..., description="Brief explanation of the code.")
    code: str = Field(..., description="Syntactically correct Python code.")
