from pydantic import Field

from data_science_agent.dtos.base.responses.code_base import CodeBase


class Code(CodeBase):
    """Response format: code generated by the LLM used to achieve the visualization goal."""
    code: str = Field(..., description="Syntactically correct code.")
