from pydantic import Field

from data_science_agent.dtos.base.responses.code_base import CodeBase


class Code(CodeBase):
    """Response format: code generated by the LLM followed by a short explanation of the code."""
    explanation: str = Field(..., description="Brief explanation of the code.")
    code: str = Field(..., description="Syntactically correct code.")
    std_err: str = Field(..., description="Error messages that occurred when executing the code.")
    std_out: str = Field(..., description="Output that was printed while executing the code.")
