from typing import Optional

from pydantic import Field

from data_science_agent.dtos.base.responses.code_base import CodeBase
from data_science_agent.dtos.en.responses.judge_verdict import JudgeVerdict


class Code(CodeBase):
    """Response format: code generated by the LLM used to achieve the visualization goal."""
    code: str = Field(..., description="Syntactically correct code.")
    std_err: Optional[str] = Field(..., description="Error messages that occurred when executing the code.")
    std_out: Optional[str] = Field(..., description="Output that was printed while executing the code.")
    needs_regeneration: Optional[bool] = Field(..., description="Indicates whether the code needs to be regenerated based on the test results.")
    regeneration_attempts: Optional[int] = Field(..., description="The number of previous attempts to regenerate the code.")
    judge_result: Optional[JudgeVerdict] = Field(..., description="The verdict given by the LLM after evaluating the code.")
