from pydantic import Field
from data_science_agent.dtos.base.responses.visualization_container_base import VisualizationContainerBase
from data_science_agent.dtos.de.responses.visualization import Visualization

class VisualizationContainer(VisualizationContainerBase):
    """Contains all visualizations."""
    visualizations: list[Visualization] = Field(..., description="List of all visualizations generated by the agent for the visualization goals.")
